// Generated by scripts/embed-sql.mjs from drizzle/*.sql — do not edit.
// One entry per migration file, in order.
export const MIGRATIONS: string[][] = [
  [
    "CREATE TABLE IF NOT EXISTS `attendance` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`date` text NOT NULL,\n\t`marked_by` text NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`client_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
    "CREATE UNIQUE INDEX IF NOT EXISTS `attendance_client_date` ON `attendance` (`client_id`,`date`);",
    "CREATE TABLE IF NOT EXISTS `body_stats` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`date` text NOT NULL,\n\t`weight_kg` real,\n\t`waist_cm` real,\n\t`chest_cm` real,\n\t`arm_cm` real,\n\t`photo` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`client_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
    "CREATE INDEX IF NOT EXISTS `body_stats_client_idx` ON `body_stats` (`client_id`,`date`);",
    "CREATE TABLE IF NOT EXISTS `meal_logs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`meal_plan_id` text NOT NULL,\n\t`date` text NOT NULL,\n\t`photo` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`client_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`meal_plan_id`) REFERENCES `meal_plan`(`id`) ON UPDATE no action ON DELETE cascade\n);",
    "CREATE UNIQUE INDEX IF NOT EXISTS `meal_logs_unique` ON `meal_logs` (`client_id`,`meal_plan_id`,`date`);",
    "CREATE TABLE IF NOT EXISTS `meal_plan` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`slot` text NOT NULL,\n\t`description` text NOT NULL,\n\t`position` integer DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`client_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
    "CREATE INDEX IF NOT EXISTS `meal_plan_client_idx` ON `meal_plan` (`client_id`);",
    "CREATE TABLE IF NOT EXISTS `packages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`total_sessions` integer NOT NULL,\n\t`start_date` text NOT NULL,\n\t`end_date` text NOT NULL,\n\t`amount` integer NOT NULL,\n\t`paid` integer DEFAULT 0 NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`client_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
    "CREATE INDEX IF NOT EXISTS `packages_client_idx` ON `packages` (`client_id`);",
    "CREATE TABLE IF NOT EXISTS `users` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`role` text NOT NULL,\n\t`name` text NOT NULL,\n\t`phone` text NOT NULL,\n\t`password_hash` text NOT NULL,\n\t`goal` text,\n\t`trainer_note` text,\n\t`active` integer DEFAULT true NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL\n);",
    "CREATE UNIQUE INDEX IF NOT EXISTS `users_phone_unique` ON `users` (`phone`);",
    "CREATE TABLE IF NOT EXISTS `workout_logs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`date` text NOT NULL,\n\t`exercise` text NOT NULL,\n\t`sets` integer NOT NULL,\n\t`reps` integer NOT NULL,\n\t`weight_kg` real DEFAULT 0 NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`client_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
    "CREATE UNIQUE INDEX IF NOT EXISTS `workout_logs_unique` ON `workout_logs` (`client_id`,`date`,`exercise`);",
    "CREATE TABLE IF NOT EXISTS `workout_plan` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`day_of_week` integer NOT NULL,\n\t`exercise` text NOT NULL,\n\t`sets` integer NOT NULL,\n\t`reps` text NOT NULL,\n\t`target_kg` real,\n\t`position` integer DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`client_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
    "CREATE INDEX IF NOT EXISTS `workout_plan_client_idx` ON `workout_plan` (`client_id`,`day_of_week`);"
  ],
  [
    "ALTER TABLE `attendance` ADD `status` text DEFAULT 'present' NOT NULL;",
    "ALTER TABLE `attendance` ADD `reason` text;",
    "ALTER TABLE `workout_logs` ADD `duration_sec` integer;",
    "ALTER TABLE `workout_plan` ADD `metric` text DEFAULT 'weight' NOT NULL;",
    "ALTER TABLE `workout_plan` ADD `target_sec` integer;"
  ],
  [
    "CREATE TABLE IF NOT EXISTS `assessments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`date` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`data` text NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`client_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
    "CREATE INDEX IF NOT EXISTS `assessments_client_idx` ON `assessments` (`client_id`,`date`);"
  ]
];
