// Bundles drizzle/*.sql into a TS module so /setup can create tables on a fresh database
// without needing the migration files on the server. Run after `drizzle-kit generate`.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const files = readdirSync("drizzle").filter((f) => f.endsWith(".sql")).sort();
const statements = files.flatMap((f) =>
  readFileSync(`drizzle/${f}`, "utf8").split("--> statement-breakpoint").map((s) => s.trim()).filter(Boolean)
    .map((s) => s.replace(/^CREATE TABLE `/, "CREATE TABLE IF NOT EXISTS `").replace(/^CREATE (UNIQUE )?INDEX `/, "CREATE $1INDEX IF NOT EXISTS `")),
);
writeFileSync("src/db/init-sql.ts", `// Generated by scripts/embed-sql.mjs — do not edit.\nexport const INIT_SQL: string[] = ${JSON.stringify(statements, null, 2)};\n`);
console.log(`Embedded ${statements.length} statements from ${files.length} file(s)`);
