// Bundles drizzle/*.sql into a TS module so the server can create or upgrade the database itself
// (via /setup and on startup) without the migration files being deployed. Run after `drizzle-kit generate`.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const files = readdirSync("drizzle").filter((f) => f.endsWith(".sql")).sort();
const migrations = files.map((f) =>
  readFileSync(`drizzle/${f}`, "utf8").split("--> statement-breakpoint").map((s) => s.trim()).filter(Boolean)
    .map((s) => s.replace(/^CREATE TABLE `/, "CREATE TABLE IF NOT EXISTS `").replace(/^CREATE (UNIQUE )?INDEX `/, "CREATE $1INDEX IF NOT EXISTS `")),
);
writeFileSync("src/db/migrations.ts", `// Generated by scripts/embed-sql.mjs from drizzle/*.sql — do not edit.\n// One entry per migration file, in order.\nexport const MIGRATIONS: string[][] = ${JSON.stringify(migrations, null, 2)};\n`);
console.log(`Embedded ${migrations.length} migration(s)`);
